name: Go Release Automation

permissions:
  contents: write
  releases: write

on:
  push:
    branches:
      - main   # trigger on pushes to main branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # use your Go version

    # 3. Build the binary for Linux
    - name: Build Go binary
      run: |
        go build -o uploader-linux main.go

    # 4. Create GitHub release and upload binary
    - name: Create Release and Upload Binary
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        body: Automated release for build ${{ github.run_number }}
        files: uploader-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
